import type { Company, HiringSignal } from "./types";

const sig = (
  id: string,
  category: HiringSignal["category"],
  title: string,
  daysAgo: number,
  source: string,
  confidence: number,
  delta: number
): HiringSignal => ({
  id,
  category,
  title,
  detectedAt: new Date(Date.now() - daysAgo * 24 * 60 * 60 * 1000).toISOString(),
  source,
  confidence,
  delta,
});

export const MOCK_COMPANIES: Company[] = [
  {
    id: "c-001",
    name: "Helix Robotics",
    domain: "helixrobotics.io",
    industry: "AI/ML",
    region: "DACH",
    headquarters: "Munich, DE",
    employees: 312,
    employeeGrowth90d: 18.4,
    openRoles: 47,
    rolesGrowth30d: 38.2,
    fundingStage: "Series C",
    lastFundingAmountM: 110,
    lastFundingMonthsAgo: 2,
    techStackShifts: 4,
    leadershipChanges90d: 2,
    description:
      "Industrial humanoid robotics platform scaling production after Series C; ramping ML and supply-chain teams.",
    predictedHiringWindowDays: 45,
    predictedRolesNext90d: 62,
    signals: [
      sig("s-101", "funding_round", "Series C closed at $110M", 60, "Crunchbase", 0.98, 1),
      sig("s-102", "hiring_velocity", "Open roles +38% in 30 days", 4, "LinkedIn Jobs", 0.92, 0.6),
      sig("s-103", "leadership_change", "New VP Manufacturing", 21, "LinkedIn", 0.88, 0.4),
      sig("s-104", "tech_stack_shift", "Adopted Ray + Kubeflow", 14, "GitHub Org", 0.74, 0.3),
    ],
  },
  {
    id: "c-002",
    name: "Northwind Pay",
    domain: "northwindpay.com",
    industry: "Fintech",
    region: "Nordics",
    headquarters: "Stockholm, SE",
    employees: 168,
    employeeGrowth90d: 9.1,
    openRoles: 22,
    rolesGrowth30d: 15.0,
    fundingStage: "Series B",
    lastFundingAmountM: 42,
    lastFundingMonthsAgo: 6,
    techStackShifts: 2,
    leadershipChanges90d: 1,
    description:
      "B2B embedded payments for Nordic SMB platforms; expanding compliance and platform teams ahead of EU PSD3.",
    predictedHiringWindowDays: 60,
    predictedRolesNext90d: 28,
    signals: [
      sig("s-201", "hiring_velocity", "Compliance roles +50%", 9, "LinkedIn Jobs", 0.81, 0.5),
      sig("s-202", "office_expansion", "New Helsinki hub announced", 30, "Press", 0.7, 0.3),
      sig("s-203", "tech_stack_shift", "Migrating to Temporal", 18, "Engineering Blog", 0.65, 0.25),
    ],
  },
  {
    id: "c-003",
    name: "Vesper Health",
    domain: "vesperhealth.ai",
    industry: "Healthtech",
    region: "UK & Ireland",
    headquarters: "London, UK",
    employees: 84,
    employeeGrowth90d: 24.6,
    openRoles: 31,
    rolesGrowth30d: 52.1,
    fundingStage: "Series A",
    lastFundingAmountM: 28,
    lastFundingMonthsAgo: 1,
    techStackShifts: 3,
    leadershipChanges90d: 2,
    description:
      "AI clinician copilot for the NHS and private hospital networks; rapid clinical-AI hiring after Series A.",
    predictedHiringWindowDays: 30,
    predictedRolesNext90d: 40,
    signals: [
      sig("s-301", "funding_round", "Series A $28M led by Index", 30, "Crunchbase", 0.97, 1),
      sig("s-302", "hiring_velocity", "Clinical AI roles +52%", 3, "LinkedIn Jobs", 0.93, 0.7),
      sig("s-303", "leadership_change", "Hired Chief Clinical Officer", 12, "LinkedIn", 0.9, 0.45),
      sig("s-304", "tech_stack_shift", "Switched to LangGraph", 7, "GitHub Org", 0.7, 0.3),
    ],
  },
  {
    id: "c-004",
    name: "Atlas Freight Cloud",
    domain: "atlasfreight.io",
    industry: "Logistics",
    region: "BeNeLux",
    headquarters: "Rotterdam, NL",
    employees: 540,
    employeeGrowth90d: 4.2,
    openRoles: 18,
    rolesGrowth30d: 6.0,
    fundingStage: "Series D+",
    lastFundingAmountM: 200,
    lastFundingMonthsAgo: 14,
    techStackShifts: 1,
    leadershipChanges90d: 0,
    description:
      "Container freight visibility platform; steady-state hiring with selective platform investments.",
    predictedHiringWindowDays: 90,
    predictedRolesNext90d: 14,
    signals: [
      sig("s-401", "hiring_velocity", "Platform roles +6%", 10, "LinkedIn Jobs", 0.6, 0.15),
      sig("s-402", "tech_stack_shift", "Adopted ClickHouse", 25, "Engineering Blog", 0.55, 0.2),
    ],
  },
  {
    id: "c-005",
    name: "Quanta Secure",
    domain: "quantasecure.com",
    industry: "Cybersecurity",
    region: "North America",
    headquarters: "Austin, US",
    employees: 220,
    employeeGrowth90d: 14.3,
    openRoles: 38,
    rolesGrowth30d: 28.4,
    fundingStage: "Series B",
    lastFundingAmountM: 65,
    lastFundingMonthsAgo: 3,
    techStackShifts: 3,
    leadershipChanges90d: 1,
    description:
      "Identity threat detection for hybrid environments; strong roles momentum across detection engineering.",
    predictedHiringWindowDays: 40,
    predictedRolesNext90d: 48,
    signals: [
      sig("s-501", "hiring_velocity", "Detection eng +28%", 5, "LinkedIn Jobs", 0.88, 0.55),
      sig("s-502", "funding_round", "Series B $65M", 90, "Crunchbase", 0.96, 0.7),
      sig("s-503", "leadership_change", "Hired VP of Threat Research", 18, "LinkedIn", 0.85, 0.4),
    ],
  },
  {
    id: "c-006",
    name: "Solivia Energy",
    domain: "solivia.eco",
    industry: "Climate Tech",
    region: "Iberia",
    headquarters: "Madrid, ES",
    employees: 96,
    employeeGrowth90d: 12.0,
    openRoles: 16,
    rolesGrowth30d: 22.0,
    fundingStage: "Series A",
    lastFundingAmountM: 19,
    lastFundingMonthsAgo: 4,
    techStackShifts: 2,
    leadershipChanges90d: 1,
    description:
      "Distributed solar marketplace; growing data and grid-ops engineering ahead of Iberian rollout.",
    predictedHiringWindowDays: 55,
    predictedRolesNext90d: 22,
    signals: [
      sig("s-601", "hiring_velocity", "Grid-ops roles +22%", 8, "LinkedIn Jobs", 0.82, 0.4),
      sig("s-602", "office_expansion", "Lisbon office opening", 21, "Press", 0.7, 0.3),
    ],
  },
  {
    id: "c-007",
    name: "Lumen Commerce",
    domain: "lumencommerce.com",
    industry: "E-Commerce",
    region: "DACH",
    headquarters: "Berlin, DE",
    employees: 410,
    employeeGrowth90d: -3.1,
    openRoles: 8,
    rolesGrowth30d: -12.0,
    fundingStage: "Series C",
    lastFundingAmountM: 70,
    lastFundingMonthsAgo: 22,
    techStackShifts: 0,
    leadershipChanges90d: 3,
    description:
      "Headless commerce platform restructuring after slow growth quarter; leadership reshuffle in progress.",
    predictedHiringWindowDays: 120,
    predictedRolesNext90d: 6,
    signals: [
      sig("s-701", "layoff_pivot", "Headcount -3% in 90d", 14, "LinkedIn", 0.78, -0.5),
      sig("s-702", "leadership_change", "New CFO + COO", 28, "LinkedIn", 0.9, 0.4),
    ],
  },
  {
    id: "c-008",
    name: "Periscope Analytics",
    domain: "periscope.ai",
    industry: "SaaS",
    region: "UK & Ireland",
    headquarters: "Dublin, IE",
    employees: 132,
    employeeGrowth90d: 11.0,
    openRoles: 24,
    rolesGrowth30d: 19.5,
    fundingStage: "Series B",
    lastFundingAmountM: 38,
    lastFundingMonthsAgo: 5,
    techStackShifts: 2,
    leadershipChanges90d: 1,
    description:
      "Self-serve analytics for product teams; opening AI-native team after Q1 revenue acceleration.",
    predictedHiringWindowDays: 50,
    predictedRolesNext90d: 30,
    signals: [
      sig("s-801", "hiring_velocity", "Open roles +19%", 6, "LinkedIn Jobs", 0.84, 0.45),
      sig("s-802", "tech_stack_shift", "AI-native rewrite (LangChain)", 12, "GitHub Org", 0.7, 0.3),
      sig("s-803", "leadership_change", "Hired Head of AI", 22, "LinkedIn", 0.86, 0.4),
    ],
  },
  {
    id: "c-009",
    name: "Cobalt Banking",
    domain: "cobaltbanking.eu",
    industry: "Fintech",
    region: "DACH",
    headquarters: "Zurich, CH",
    employees: 760,
    employeeGrowth90d: 2.0,
    openRoles: 12,
    rolesGrowth30d: 4.0,
    fundingStage: "Public",
    lastFundingAmountM: 0,
    lastFundingMonthsAgo: 0,
    techStackShifts: 1,
    leadershipChanges90d: 1,
    description:
      "Listed neobank; conservative hiring with focused investments in regulatory and risk engineering.",
    predictedHiringWindowDays: 100,
    predictedRolesNext90d: 10,
    signals: [
      sig("s-901", "hiring_velocity", "Risk eng +4%", 11, "LinkedIn Jobs", 0.55, 0.1),
      sig("s-902", "leadership_change", "New Head of Risk Eng", 19, "LinkedIn", 0.8, 0.3),
    ],
  },
  {
    id: "c-010",
    name: "Rivermark Bio",
    domain: "rivermarkbio.com",
    industry: "Healthtech",
    region: "North America",
    headquarters: "Boston, US",
    employees: 58,
    employeeGrowth90d: 32.0,
    openRoles: 19,
    rolesGrowth30d: 41.0,
    fundingStage: "Seed",
    lastFundingAmountM: 12,
    lastFundingMonthsAgo: 1,
    techStackShifts: 2,
    leadershipChanges90d: 1,
    description:
      "Computational biology platform; aggressive seed-stage hiring following oversubscribed seed extension.",
    predictedHiringWindowDays: 25,
    predictedRolesNext90d: 24,
    signals: [
      sig("s-1001", "funding_round", "Seed extension $12M", 30, "Crunchbase", 0.95, 0.8),
      sig("s-1002", "hiring_velocity", "Comp-bio roles +41%", 4, "LinkedIn Jobs", 0.9, 0.7),
      sig("s-1003", "leadership_change", "Hired Head of Platform", 16, "LinkedIn", 0.83, 0.45),
    ],
  },
  {
    id: "c-011",
    name: "Skyforge AI",
    domain: "skyforge.ai",
    industry: "AI/ML",
    region: "North America",
    headquarters: "San Francisco, US",
    employees: 41,
    employeeGrowth90d: 48.0,
    openRoles: 27,
    rolesGrowth30d: 60.0,
    fundingStage: "Series A",
    lastFundingAmountM: 35,
    lastFundingMonthsAgo: 1,
    techStackShifts: 5,
    leadershipChanges90d: 2,
    description:
      "Foundation model infra startup; pulling senior systems engineers after Series A.",
    predictedHiringWindowDays: 20,
    predictedRolesNext90d: 36,
    signals: [
      sig("s-1101", "funding_round", "Series A $35M", 28, "Crunchbase", 0.96, 0.9),
      sig("s-1102", "hiring_velocity", "Open roles +60%", 2, "LinkedIn Jobs", 0.94, 0.85),
      sig("s-1103", "leadership_change", "Hired VP Eng (ex-Anthropic)", 10, "LinkedIn", 0.92, 0.6),
      sig("s-1104", "tech_stack_shift", "Switched orchestrator to Modal", 15, "GitHub Org", 0.78, 0.35),
    ],
  },
  {
    id: "c-012",
    name: "Greta Ops",
    domain: "gretaops.com",
    industry: "SaaS",
    region: "Nordics",
    headquarters: "Copenhagen, DK",
    employees: 73,
    employeeGrowth90d: 8.0,
    openRoles: 14,
    rolesGrowth30d: 12.0,
    fundingStage: "Seed",
    lastFundingAmountM: 6,
    lastFundingMonthsAgo: 7,
    techStackShifts: 1,
    leadershipChanges90d: 0,
    description:
      "DevOps automation tooling for mid-market; modest momentum, watching for follow-on funding.",
    predictedHiringWindowDays: 70,
    predictedRolesNext90d: 16,
    signals: [
      sig("s-1201", "hiring_velocity", "Open roles +12%", 7, "LinkedIn Jobs", 0.7, 0.3),
      sig("s-1202", "tech_stack_shift", "Added Bun runtime", 20, "GitHub Org", 0.55, 0.15),
    ],
  },
];
