#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Hermes · Hostinger env bootstrap
# -----------------------------------------------------------------------------
# Reads secrets from your shell ENVIRONMENT (NEVER from a committed file)
# and writes a fresh `.env` next to this service. Designed to be run ONE TIME
# on the server, never in CI, never on a laptop you don't trust.
#
# Usage on the Hostinger box (replace ... with the real values):
#
#   export OPENROUTER_API_KEY='sk-or-v1-...'
#   export HERMES_API_KEY="$(openssl rand -hex 32)"   # generate, copy to Vercel
#   bash services/hermes/scripts/install-env.sh
#   pm2 restart rsg-hermes
#
# After running:
#   - .env exists in services/hermes (gitignored, mode 600)
#   - the only copy of OPENROUTER_API_KEY now lives there
#   - your shell history may still have `export …` — clear it:
#       history -d $(history | tail -n 5 | head -n 1 | awk '{print $1}')
#       unset OPENROUTER_API_KEY HERMES_API_KEY
#
# This script does NOT write any secret to stdout. It does NOT log values.
# -----------------------------------------------------------------------------

set -euo pipefail

# Resolve the directory containing this script, then cd into services/hermes
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$SERVICE_DIR"

require() {
  local name="$1"
  if [ -z "${!name:-}" ]; then
    echo "✗ env var $name is required (export it before running)" >&2
    exit 1
  fi
}

require OPENROUTER_API_KEY
require HERMES_API_KEY

# Optional knobs — fall back to safe defaults
: "${HERMES_HOST:=0.0.0.0}"
: "${HERMES_PORT:=4001}"
: "${OPENROUTER_MODEL_FAST:=openai/gpt-4o-mini}"
: "${OPENROUTER_MODEL_DEEP:=anthropic/claude-3.5-haiku}"
: "${OPENROUTER_MAX_TOKENS_FAST:=600}"
: "${OPENROUTER_MAX_TOKENS_DEEP:=1500}"
: "${OPENROUTER_TIMEOUT_MS:=25000}"
: "${OPENROUTER_REFERER:=https://rsg-hiring-radar.local}"
: "${OPENROUTER_APP_NAME:=RSG Hermes}"
: "${HERMES_RPM_FAST:=30}"
: "${HERMES_RPM_DEEP:=6}"
: "${HERMES_RPD_FAST:=3000}"
: "${HERMES_RPD_DEEP:=200}"

TARGET="$SERVICE_DIR/.env"

# Refuse to overwrite without an explicit FORCE=1
if [ -f "$TARGET" ] && [ "${FORCE:-0}" != "1" ]; then
  echo "✗ $TARGET already exists. Re-run with FORCE=1 to overwrite." >&2
  exit 1
fi

umask 077
cat > "$TARGET" <<EOF
# Generated by install-env.sh — do NOT commit, do NOT email, do NOT paste.
HERMES_HOST=$HERMES_HOST
HERMES_PORT=$HERMES_PORT
HERMES_API_KEY=$HERMES_API_KEY

OPENROUTER_API_KEY=$OPENROUTER_API_KEY
OPENROUTER_MODEL_FAST=$OPENROUTER_MODEL_FAST
OPENROUTER_MODEL_DEEP=$OPENROUTER_MODEL_DEEP
OPENROUTER_MAX_TOKENS_FAST=$OPENROUTER_MAX_TOKENS_FAST
OPENROUTER_MAX_TOKENS_DEEP=$OPENROUTER_MAX_TOKENS_DEEP
OPENROUTER_TIMEOUT_MS=$OPENROUTER_TIMEOUT_MS
OPENROUTER_REFERER=$OPENROUTER_REFERER
OPENROUTER_APP_NAME=$OPENROUTER_APP_NAME

HERMES_RPM_FAST=$HERMES_RPM_FAST
HERMES_RPM_DEEP=$HERMES_RPM_DEEP
HERMES_RPD_FAST=$HERMES_RPD_FAST
HERMES_RPD_DEEP=$HERMES_RPD_DEEP
EOF

chmod 600 "$TARGET"
echo "✓ wrote $TARGET (mode 600, gitignored)"
echo "  next: pm2 restart rsg-hermes && curl http://localhost:$HERMES_PORT/health"
